name: deploy

on:
  push: { branches: [ core ] }
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: { name: deploy-to-s3 }
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v3
      - env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync --delete ./page "${{ vars.BUCKET }}" \
          && aws cloudfront create-invalidation --paths "/*" --distribution-id "${{ vars.CFDIST }}"
